
patterns:
  ip_regex: '([0-9]{1,3}\.){3}[0-9]{1,3}'
  mac_regex: '([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}'
  mitre_regex: 'T[0-9]{4}(\.[0-9]{3})?'  
  url_regex: '(https?:\/\/)?([a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,6}(\/[a-zA-Z0-9\-\._\?\,'\/\\+&amp;%\$#\=~]*)?'
  domain_regex: '([a-zA-Z0-9\-]+\.)+[a-zA-Z]{2,6}'
  md5_regex: '[a-fA-F0-9]{32}'

lists:
  ip_list:
    - 192.168.1.1
    - 10.0.0.1
  mac_list:
    - 00:1A:2B:3C:4D:5E
  mitre_list:
    - T0845
  domain_list:
    - maliciousdomain.com
  url_list:
    - http://maliciousdomain.com/phishing
  protocol_list:
    - modbus
  md5_list:
    - 5d41402abc4b2a76b9719d911017c592

logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'
  output_file: 'script.log'
